# Docker Compose File Template


version: "3.8"
services:
  apache:
    image: httpd:latest
    container_name: my_apache
    labels:
      - "maintainer=gri.daniel@gmail.com"
      - "author=grigore daniel"
      - "comments=nothing special"
    environment:
      - "var1=val1"
      -  var2="val2"
    networks:
      - default
      ipv4_address: 192.168.1.10
    dns:
      - 8.8.8.8
      - 9.9.9.9
    dns_search:
      - domain1.com
      - domain2.com
    domainname: foo.com
    hostname: foo
    privileged: false
    stdin_open: true
    tty: true
    volumes:
      source: ./mydata
      target: /data
      read_only: true
    ports:
      - 8080/tcp
      - "6060:80/tcp"
      - "3000-3005"
    user: custom_user
    working_dir: /code
    command: ["echo", "hello world"]
    depends-on:
      - db
      - nothing
    restart: always
    entrypoint: ["php", "-d", "/bin/stuff.php"]

# Everything under this section is about defining networks      
# We can use the networks defined here in the services above
networks:
  default:
    external: true
    name: bridge
  macnet1:
    driver: macvlan
    driver_opts:
      parent: enp0s8
      macvlan_mode: bridge
   attachable: true
   ipam:
     driver: default
     config:
       - subnet: 192.1681.0/24



