# Docker Compose File Template With Coments
# If we are using compose.yaml or compose.yml there is no need for the version
# You should use docker-compose config to check the compose file

# The following objects support alternative syntax (list): labels, environment 

version: "3.8"
services:
  apache:
    cpu_count: 2
    cpu_percentage: 30
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/sda:/dev/xvda:rwm"
    image: httpd:latest
    build: .
    init: true
# container_name doesn't work with scale
    hostname: foo
    container_name: my_apache
    labels:
      - "maintainer=gri.daniel@gmail.com"
      - "author=grigore daniel"
      - "comments=nothing special"
    env_file:    
      - .env
    environment:
      - "var1=val1"
      - "var2=val2"
# network_mode: "host" | "none" | "service"
# If you don't specify any other settings for networking, a list with network names can be enough
    networks:
      - default
      - custom_bridge

# If you want to specify custom ip, alias, priority and link_local_ip then you should use this syntax
#   networks:
#     my_new_network:
#       ipv4_address: 1.2.3.4
#       aliases:
#         -one
#         -who
#         -two
#       priority: 100
# aliases declares alternative hostnames for the service on the network. 
# Other containers on the same network can use either the service name or an alias 
# to connect to one of the service's containers.
#
# Docker Compose default network.
# If we do not define a specific network, compose sets up a single default network that each container will join.
# This default network is given a name based on the project's name which in turn is based on the 
# name of the directory it lives in. 
# The name of the project can be overriden with --project-name runtime directive or with the
# COMPOSE_PROJECT_NAME environment variable



# If you're not clear about the difference between ports and expose in compose here's a quick overview:
# Expose ports without publishing them to the host machine - they’ll only be accessible to linked services.
# Only the internal port can be specified.
    expose:
      - "3000"
    ports:
      - "8080/tcp"
      - "6060:80/tcp"
      - "3000-3005"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    dns_search:
      - domain1.com
      - domain2.com
    domainname: foo.com
# Add these extra hosts to container /etc/hosts
    extra_hosts:
      - "somehost:1.2.3.4"
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    stdin_open: true
    tty: true
    volumes:
      source: ./mydata
      target: /data
      read_only: true
    user: custom_user
    working_dir: /code
    depends-on:
      - db
      - nothing
    restart: always
    entrypoint: 
      - php
      - d
      - /bin/stuff.php
    command: apachectl -k start
    command: ["/usr/local/bin/httpd","-DFOREGROUND"]
    command: null
    configs:
    secrets:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://1.2.3.4:123"

# Everything under this section is about defining networks      
# We can use the networks defined here in the services above
networks:
  default:
    external: true
    name: bridge
  macnet1:
    driver: macvlan
    driver_opts:
      parent: enp0s8
      macvlan_mode: bridge
      ipvlan_mode: l2 | l3
    attachable: true
    ipam:
      driver: default
      config:
       - subnet: 192.168.1.0/24
         ip_range: 192.168.1.128/25
         gateway: 192.168.1.1
         aux_addresses:
           host1: 192.168.1.10
           host2: 192.168.1.11
  hostnet:
    external: true
    name: host

volumes:
  example:
    driver_opts:
      type: "nfs"
      o: "addr=10.40.0.199,nolock,soft,rw"
      device: ":/docker/example"

  db-data:
    external: true
      name: actual-name-of-volume


